app:
  port: 8088

server:
  port: ${app.port}

spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: SA
    password: ""
  jpa:
    hibernate:
      ddl-auto: create

evaluacion:
  openapi:
    url: http://localhost:${app.port}
